### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by JimScope** [codeforms/Punica-CSS-Framework#4]
Consider adding support for light and dark themes

**Comment by UnderlineWords** [comment]
I've been working on the theming for a while already. 
I will deploy it with version 2.0.

punica.scss;
```scss
$active-theme = light; // light, dark, another etc.
```

themes.scss (new file @v2.0);
```scss
$themes: (
    light: (
	'primary-color': #0a8fff,
	'success-color': #2ec4b6,
        ...
        ...
       ),
   dark: (.....),
   another: (.....),
   // add your own theme...
)
```
example label variables;
```scss
$label-styles	: (
	"primary"	: theme('primary-color'), // active theme's primary color
	"success"	: theme('success-color'),
       ...
);
```

**Comment by JimScope** [comment]
English: Interesting. Do you plan to adopt a more modern design system by default? Maybe with some details of Skeumorphism. If so, contribute as it seems to me a framework with a lot of future. 😊

**Comment by UnderlineWords** [comment]
Thanks for your comment @JimScope 
Glassmorphism / Skeumorphism / Neumorphism / Brutalism (UI) etc etc ... 
Actually I'm not much interested in UI trends :smiley:

In the punica project, my primary goal is more about the fully customizable development process rather than the production. 

So users can customize, compile and use the Punica as they wish.
It can make/apply any design trend itself. :taco:
